### ISSUE TITLE
Trouble While Enabling

### ISSUE THREAD

**Issue by xRugHere** [Andre601/IAxPresenceFootsteps#2]
**Hey! just had a question about the plugin and what a potential fix might be for this error in console. I want to assume it's either because I'm using 1.18.1, or it's one of the many plugins I'm currently using (This one's probably the case). Sorry to trouble you:**

[14:04:02 ERROR]: Error occurred while enabling IAxPresenceFootsteps v1.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "ch.andre601.iaxpresencefootsteps.util.message.MessageUtil.sendMessage(String, Object[])" because the return value of "ch.andre601.iaxpresencefootsteps.IAxPresenceFootsteps.getMessageUtil()" is null
        at ch.andre601.iaxpresencefootsteps.IAxPresenceFootsteps.onEnable(IAxPresenceFootsteps.java:34) ~[IAxPresenceFootsteps-1.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:04:02 INFO]: [IAxPresenceFootsteps] Disabling IAxPresenceFootsteps v1.2.0

**Plugins (50):** AnimationsCore, AnnouncerPlus, ArmorStandAdjustor, BetonQuest, ChatManager, CinematicTool, Citizens, CommandPanels, CustomFishing, DeluxeMenus, Ersatz*, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GHolo, HolographicDisplays, HolographicDisplaysAddon*, HoloMobHealth, IAxPresenceFootsteps, ItemsAdder, LibsDisguises, LightAPI, LoneLibs, LuckPerms, MMOCore, MMOItems, Multiverse-Core, MythicLib, MythicMobs, Parties, PlaceholderAPI, PluginConstructorAPI, PowerCamera, ProtocolLib, ServerTutorialPlus*, ShopGUIPlus, ShopGUIPlus-SellGUI, spark, TAB, Test, UltraBar, Vault, ViaVersion, VoxelSniper, WorldGuard

**Comment by Andre601** [comment]
Please use the issue template. Thanks
